/*
 * Copyright (C) 2021 guanxiongwei
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.stream.extension.meta;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Task execution step info.
 * @author guanxiongwei
 *
 */
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Data
public class TaskStep {

    // Task id, randomly generated by uuid.
    private String taskId;

    // Procedure graph name.
    private String graphName;

    // Target node name.
    private String nodeName;

    // Jsonfied string represent of data transfered between services.
    private byte[] streamTransferData;

    // Create time.
    private long createTime;

    // Execution status.
    private String status;

    // Database unique key in case needed.
    private long id;

}
