package org.stream.extension.meta;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@NoArgsConstructor
@AllArgsConstructor
@Builder
@Data
public class TaskStep {

    // Task id, randomly generated by uuid.
    private String taskId;

    // Procedure graph name.
    private String graphName;

    // Target node name.
    private String nodeName;

    // Jsonfied string represent of data transfered between services.
    private byte[] streamTransferData;

    // Create time.
    private long createTime;

    // Execution status.
    private String status;

    // Database unique key in case needed.
    private long id;

}
